spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/WORDMASTER
    username: word_master_user
    password: password

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        hbm2ddl:
          auto: validate
    open-in-view: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: true
    enabled: true
    contexts: dev